[template]
keys = [
  "certs",
  "services",
  "tcp-services"
]

owner = "haproxy"
mode = "0644"
src = "haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"

check_cmd = "/usr/local/bin/check-haproxy {{ .src }}"
reload_cmd = "/usr/local/bin/reload-haproxy"
